[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "django-rqscheduler4"
packages = [
    { include = "scheduler" },
]
version = "2022.4"
description = "A database backed job scheduler for Django RQ with Django"
readme = "README.md"
keywords = ["django", "rq", "django-rq", "rq-scheduler"]
authors = [
    "Daniel Moran <daniel.maruani@gmail.com>"
]
license = "MIT"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Web Environment',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.10',
    'Framework :: Django',
    'Framework :: Django :: 4.0',
]
homepage = "https://github.com/cunla/django-rqscheduler"

[tool.poetry.dependencies]
python = "^3.8"
django = [
    {version="^3.2", markers="python_version == '3.9'"},
    {version="^4.0", markers="python_version >= '3.10'"}
]
django-model-utils = "^4.2.0"
django-rq = "^2.4.1"
rq-scheduler = "^0.11.0"
pytz = "^2021.3"
croniter = "^1.2.0"

[tool.poetry.dev-dependencies]
factory_boy = "3.2.1"
poetry = "~1.1"
coverage = "^6.2"
